# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/latest/overview/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/latest/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2016.4.15  4.10.12  2.1.9  2018-12 (LTS)
# SIMP 6.0      4.8.2    2.1.9  TBD
# SIMP 6.1      4.10.6   2.1.9  TBD
# SIMP 6.2      4.10.12  2.1.9  TBD
# SIMP 6.3      5.5.7    2.4.4  TBD***
# PE 2018.1     5.5.6    2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock
  - gem update --system

jobs:
  include:
    - stage: test
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes TRUSTED_NODE_DATA=yes PUPPET_VERSION="~> 5.5.6"
      script:
        - bundle exec rake test

    - stage: test
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes TRUSTED_NODE_DATA=yes PUPPET_VERSION="~> 5.0"
      script:
        - bundle exec rake test

